# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ 
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "sd_mod" ];
      kernelModules = [ ];
    };
    extraModulePackages = with pkgs; [ linuxPackages_6_12.sysdig linuxPackages_6_12.tmon ];
    tmp.useTmpfs = true;
    kernelModules = [ "kvm-amd" ];
  };
  
  boot.kernelParams = [
  # "isolcpus=1,2,3,4,5,6,7,8,9,10,11"
  # "loglevel=7"
  ];
  boot.consoleLogLevel = 7;

  fileSystems = {
    "/" = { 
      device = "/dev/disk/by-label/nixos";
      fsType = "ext4";
    };
  };

  hardware = {
    bluetooth = {
      enable = true;
      settings = {
        General = {
          Name = "Hello";
          ControllerMode = "dual";
          FastConnectable = "true";
          Experimental = "true";
        };
      };
    };

    pulseaudio = {
      enable = false;
      #package = pkgs.pulseaudioFull;
    #  systemWide = true;
    };
    nvidia = {
      package = config.boot.kernelPackages.nvidiaPackages.beta;
      open = false;
      modesetting.enable = true; 
    };
  };

  swapDevices = [ ];

  nix.settings.max-jobs = lib.mkDefault 12;
}
