# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ 
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "sd_mod" ];
      kernelModules = [ ];
    };
    extraModulePackages = [ pkgs.linuxPackages_5_10.sysdig ];
    tmpOnTmpfs = true;
    kernelModules = [ "kvm-amd" ];
  };
  
  boot.kernelParams = [
  # "isolcpus=1,2,3,4,5,6,7,8,9,10,11"
  # "loglevel=7"
  ];
  boot.consoleLogLevel = 7;

  fileSystems = {
    "/" = { 
      device = "/dev/disk/by-label/nixos";
      fsType = "ext4";
    };
  };

  hardware = {
    bluetooth.enable = true;
    pulseaudio = {
      enable = true;
      package = pkgs.pulseaudioFull;
      systemWide = true;
    };
    nvidia = {
      modesetting.enable = true;
      
    };
  };

  swapDevices = [ ];

  nix.maxJobs = lib.mkDefault 12;
}
